package-lock.json
package.json
src/app/casos-activos/page.js
src/app/page.js
src/app/solicitar-ayuda/page.js
src/app/voluntometro/page.js
src/components/OfferHelp.js
src/components/SolicitudCard.js
src/components/map/map.js
src/helpers/constants.js
src/helpers/format.js

Solucion de conflictos, mapa con todos los avisos

feat: new map functionality - removed merge problems

---

.gitignore
docker/docker-compose.yaml
src/lib/supabase.js

- **chore: update .gitignore & next config**
- **feat: docker compose local db**

feat: local db

---

src/app/auth/page.js
src/components/UserInfo.js
src/components/auth/Login.js
src/components/auth/SocialButton.js
src/components/layout/Sidebar.js

- He creado la página de auth integrando los formularios de @robertobobby1 
- He añadido el login con Google
- He añadido en el sidebar un link para iniciar sesión
- He añadido el nombre del usuario en el sidebar si está logeado
- He añadido un link para cerrar sesión en el sidebar

feat(auth): add google auth and create auth page

---

src/app/punto-recogida/page.js
src/helpers/utils.js

se ha arreglado el comportamiento del input **Contact Number** del formulario punto de recogida

fix(punto-recogida) - fix contact number not filling correctly

---

src/app/casos-activos/solicitudes/page.js

https://trello.com/c/2PlpNZv8/54-filtro-tipo-de-ayuda-necesaria-en-solicitudes-de-ayuda

Help type filter

---

src/app/page.js
src/components/Modal.js
src/components/auth/PhoneNumberDialog.js
src/lib/service.js

Si un usuario no tiene un número de teléfono asociado en Supabase, verán en la página principal un diálogo para introducir su número de teléfono. Este diálogo no se puede cerrar.

Usuarios sin un telf tienen que añadir uno

---

src/app/page.js
src/app/solicitar-ayuda/page.js

Mensage alerta personas mayores

---

package-lock.json
package.json
src/types/DataPoints.ts
src/types/Markers.ts
src/types/Requests.ts
src/types/common.ts
tsconfig.json

Para no perder el trabajo hecho.
Ademas así se puede trabajar en ambos maneras desde ahora

feat(Typescript) Init para utilizar ambos ts o js

---

src/app/solicitar-ayuda/page.js
src/app/voluntometro/page.js
src/components/OfferHelp.js
src/components/PhoneInput.js
src/components/auth/PhoneNumberDialog.js
src/components/auth/SignUp.js
src/helpers/format.js
src/lib/service.js

* Acciones de escribir en Supabase sólo se deberían hacer a través del Service
* Crear un componente común para añadir número de teléfono. Dejar claro que el prefijo es el español, y ya viene incluido
* Formatear el número de teléfono en submit para que esté consistente en la DB
* Cambiar todos los entry point de número de teléfono al normalizado
---
Voluntometro: 
Solicitar ayuda:
Crear cuenta:

Normalizar numeros de telefono

---

src/components/layout/EmergencyLayout.js
src/components/layout/Footer.js

https://trello.com/c/gDMqNLa5/69-a%C3%B1adir-disclaimer-de-que-somos-voluntarios

Add footer

---

src/app/page.js
src/app/solicitar-ayuda/page.js

Pedir a la gente que no colapse la linea y ofrecer alternativas

---

src/app/solicitar-ayuda/page.js
src/app/voluntometro/page.js
src/components/OfferHelp.js

https://trello.com/c/QzVzfBTm/83-quitar-bot%C3%B3n-a%C3%B1adir-pueblo

Remove add town buttons

---

src/app/page.js

https://trello.com/c/vrb6Afxe/76-puntos-m%C3%A9dicos-oficiales

Add medical centers

---

src/app/casos-activos/puntos/page.js
src/app/page.js

Para hacerlo mas facil a la gente, añadir la dirección como un enlace a google maps:

Address as google maps links

---

src/helpers/constants.js

Cambiar títulos para una mayor comprensión de los tipos de ayuda.

feat(pedir-ayuda) - Update help type options for clarity and consistency

---

src/app/page.tsx
src/app/voluntometro/page.js
src/components/layout/EmergencyLayout.js

Todas las paginas tienen un layout comun que define la anchura maxima:
Landing
Voluntometro
Solicitar ayuda
Ofrecer ayuda
Punto de recogida
Punto de entrega

Normalizar los layouts entre paginas

---

src/app/solicitar-ayuda/page.js
src/components/OfferHelp.js
src/components/RequestHelp.js
src/components/auth/PhoneNumberDialog.js
src/components/auth/SignUp.js
src/helpers/format.js
src/helpers/utils.js

Esto es una PR solo para actualizar la carpeta de una utility. Si no, la PR de feature sería demasiado grande para revisar

Mover utility a una carpeta sin import de server components

---

src/app/solicitar-ayuda/page.js
src/components/OfferHelp.js

https://trello.com/c/yjeY1B8H/89-evitar-pedir-datos-personales-en-el-form-una-vez-loggeados

Use sessiond data when requesting something

---

src/components/AddressAutocomplete.js

There is a bug with `nominatim.openstreetmap.org`. We're sending a request per character typed into the input, so we're sending _lots_ of requests very fast and they're blocking us.
https://discord.com/channels/1302208697870712843/1302743710756372574/1303728114064429188

Fix nominatim.openstreetmap.org. Execute one request one

---

src/app/casos-activos/mapa/page.tsx
src/components/PickupPoint.tsx
src/components/icons/MapPinFilled.tsx
src/components/map/map.tsx

Cambiar icono del mapa a la versión "filled"

---

src/app/casos-activos/puntos/page.js

```
Error general: TypeError: e.city is null
NextJS 11
```

Fix NRE in Puntos de recogida

---

src/app/solicitar-ayuda/_components/Form/FormContainer.tsx
src/app/solicitar-ayuda/_components/Form/FormRenderer.tsx

https://trello.com/c/0WJ8amaW/91-ux-explicabilidad-del-correo
Testing:
No autenticado:
Autenticado (como estaba antes):

feat(solicitar-ayuda): Improved explanation of why email is needed for unauthenticated users

---

src/app/casos-activos/ofertas/page.js
src/app/casos-activos/solicitudes/page.js
src/app/ofertas/page.js
src/app/solicitudes/page.js
src/app/voluntometro/page.js
src/components/AsignarSolicitudButton.tsx
src/components/OfferCard.js
src/components/OfferHelp.js
src/components/SolicitudCard.tsx
src/components/SolicitudHelpCount.tsx
src/components/TownCardInfo.tsx
src/components/layout/EmergencyLayout.tsx

https://trello.com/c/dHY0Am3X/80-mejoras-en-volunt%C3%B3metro

refactor: voluntometro code & UI | new style for cards

---

src/app/casos-activos/mapa/page.tsx

Filter out finishede requests from map

Remove finished from map

---

src/constants/phoneNumber.ts

Usar el numero del call center que tenemos en CRM, las llamadas son atendidas por el grupo de agentes que tenemos trabajando.
No mergear aun!! Seguimos configurando el servidor voip

Use call center number

---

next.config.mjs
package.json

Ya que se está usando Nextjs 15 sugiero añadir React Compiler para optimización automática del rendimiento.
Fácilmente reversible si surge algún problema.
https://nextjs.org/docs/app/api-reference/next-config-js/reactCompiler

add react-compiler 

---

src/helpers/constants.ts
src/types/database.ts
supabase/migrations/20241111081800_add_help_types.sql

https://trello.com/c/vUE1Y80f/79-nuevos-tipos-de-ayuda-necesarios

Añadir nuevos tipos de ayuda

---

src/components/CRMNotes.tsx
src/components/SolicitudCard.tsx
src/helpers/constants.ts

feat(notes): Enable notes edition to moderators

---

src/app/politica-privacidad/page.tsx
src/components/CheckboxLegalText.tsx
src/components/HelpOffers/HelpOfferForm.tsx
src/components/HelpRequests/HelpRequestForm.tsx

Añadir nueva política de privacidad e información en los formularios

---

src/components/OfferCard.tsx
src/components/PhoneInfo.tsx
src/components/SolicitudCard.tsx
src/types/Requests.ts

This reverts commit 7db10b76010e654cf4953dff038376445422cebd.

Revert "fix: remove contact info too"

---

src/app/auth/page.tsx
src/app/casos-activos/solicitudes/index.tsx
src/app/casos-activos/solicitudes/page.tsx
src/app/page.tsx

- quitar uno de los dos banners del home
- reducir tamano del banner de encima del login(donde solicitar ayuda)

feat: remove old banner and update existing one
